'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';

export const generateMockTestMetadata = async (topic: string) => {
  try {
    const response = await ai.generate({
      prompt: `You are an expert SEO copywriter and educator for a mock test platform. 
      The admin wants to create a mock test about: "${topic}".
      Please generate the following fields for this mock test:
      - title: A catchy, SEO-friendly title (e.g., "WBCS Prelims Full Length Mock Test 1").
      - slug: A URL-friendly slug based on the title (e.g., "wbcs-prelims-mock-test-1").
      - description: A compelling, 2-3 sentence meta description to attract students and rank well on Google.
      - instructions: A helpful list of instructions for taking the exam (e.g., mentioning negative marking, time limits, or general tips). Use line breaks (\\n) to format the instructions nicely, keeping points on separate lines.`,
      output: {
        schema: z.object({
          title: z.string(),
          slug: z.string(),
          description: z.string(),
          instructions: z.string(),
        })
      }
    });

    // Genkit puts structured output in response.output
    const data = response.output;

    return { success: true, data };
  } catch (error: any) {
    console.error("AI Generation failed:", error);
    const msg = error?.message || error?.toString() || "Unknown error occurred";
    return { success: false, error: msg };
  }
};

export const generateImagePrompt = async (title: string, description: string) => {
  try {
    const response = await ai.generate({
      prompt: `You are an expert prompt engineer for Midjourney and Stable Diffusion.
      The admin wants to create a highly attractive feature image for a mock test.
      Test Title: "${title}"
      Test Description: "${description}"
      
      Generate a highly detailed, stunning, premium, and professional image generation prompt.
      The prompt should describe a beautiful, modern, educational or abstract aesthetic suitable for a high-end learning platform's mock test thumbnail.
      Include lighting details, style (e.g., 3D render, glassmorphism, cinematic lighting, 8k resolution, photorealistic).
      Do not include any text in the image.
      Return ONLY the raw prompt string, nothing else.`,
    });

    return { success: true, prompt: response.text.trim() };
  } catch (error: any) {
    console.error("AI Prompt Generation failed:", error);
    return { success: false, error: error?.message || "Unknown error occurred" };
  }
};

export const generateImageWithGemini = async (prompt: string) => {
  try {
    const response = await ai.generate({
      model: 'googleai/imagen-3.0-generate-001',
      prompt: prompt,
      output: { format: 'media' }
    });
    
    // Attempt to extract the generated image data URL
    const media = response.media;
    let imageUrl = '';
    
    if (media && Array.isArray(media) && media.length > 0 && media[0].url) {
      imageUrl = media[0].url;
    } else if (response.text && response.text.startsWith('data:image')) {
      imageUrl = response.text;
    } else if ((response as any).message?.content?.[0]?.media?.url) {
      imageUrl = (response as any).message.content[0].media.url;
    }

    if (!imageUrl) {
      throw new Error("No image generated by the model. Make sure Imagen API is enabled.");
    }

    return { success: true, imageUrl };
  } catch (error: any) {
    console.error("AI Image Generation failed:", error);
    return { success: false, error: error?.message || "Unknown error occurred" };
  }
};
