'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';

export const generateMockTestMetadata = async (topic: string, testType: string = "Mock Test") => {
  try {
    const response = await ai.generate({
      prompt: `You are an expert SEO copywriter and educator for a learning platform. 
      The admin wants to create a "${testType}" about: "${topic}".
      Please generate the following fields for this ${testType}:
      - title: A catchy, SEO-friendly title that MUST explicitly include the phrase "${testType}".
      - slug: A URL-friendly slug based on the title.
      - description: A compelling, 2-3 sentence meta description to attract students and rank well on Google.
      - instructions: A comprehensive and highly detailed list of instructions for taking the exam. Generate at least 5-8 detailed instruction points covering negative marking, time management, cheating policies, submission guidelines, and general tips. Return this as an array of strings, where each string is a single instruction point.
      
      IMPORTANT: If the topic is related to West Bengal exams (like WBCS, TET, PSC), or the topic implies a Bengali audience, you MUST generate the title, description, and instructions in Bengali.`,
      output: {
        schema: z.object({
          title: z.string(),
          slug: z.string(),
          description: z.string(),
          instructions: z.array(z.string()),
        })
      }
    });

    // Genkit puts structured output in response.output
    const data = response.output;
    const finalData = {
      ...data,
      instructions: Array.isArray(data?.instructions) ? data.instructions.map(i => `* ${i}`).join('\n') : data?.instructions
    };

    return { success: true, data: finalData };
  } catch (error: any) {
    console.error("AI Generation failed:", error);
    const msg = error?.message || error?.toString() || "Unknown error occurred";
    return { success: false, error: msg };
  }
};

export const generateImagePrompt = async (title: string, description: string) => {
  try {
    const response = await ai.generate({
      prompt: `You are an expert prompt engineer for Midjourney and Stable Diffusion.
      The admin wants to create a highly attractive feature image for a mock test.
      Test Title: "${title}"
      Test Description: "${description}"
      
      Generate a highly detailed, stunning, premium, and professional image generation prompt.
      The prompt should describe a beautiful, modern, educational or abstract aesthetic suitable for a high-end learning platform's mock test thumbnail.
      Include lighting details, style (e.g., 3D render, glassmorphism, cinematic lighting, 8k resolution, photorealistic).
      Do not include any text in the image.
      Return ONLY the raw prompt string, nothing else.`,
    });

    return { success: true, prompt: response.text.trim() };
  } catch (error: any) {
    console.error("AI Prompt Generation failed:", error);
    return { success: false, error: error?.message || "Unknown error occurred" };
  }
};

export const generateImageWithGemini = async (prompt: string) => {
  try {
    const response = await ai.generate({
      model: 'googleai/imagen-3.0-generate-001',
      prompt: prompt,
      output: { format: 'media' }
    });
    
    // Attempt to extract the generated image data URL
    const media = response.media;
    let imageUrl = '';
    
    if (media && Array.isArray(media) && media.length > 0 && media[0].url) {
      imageUrl = media[0].url;
    } else if (response.text && response.text.startsWith('data:image')) {
      imageUrl = response.text;
    } else if ((response as any).message?.content?.[0]?.media?.url) {
      imageUrl = (response as any).message.content[0].media.url;
    }

    if (!imageUrl) {
      throw new Error("No image generated by the model. Make sure Imagen API is enabled.");
    }

    return { success: true, imageUrl };
  } catch (error: any) {
    console.error("AI Image Generation failed:", error);
    return { success: false, error: error?.message || "Unknown error occurred" };
  }
};
